# Site settings
email: 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: The Bela blog
description: A blog about Bela.
url: ""
twitter_username: 
default_img: http://i.imgur.com/tthpnHa.gifv

# Profile settings
name: 
profile_img: 
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
