# Site settings
email: info@bela.io
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Bela Blog
description: 
url: "localhost:4000"
twitter_username: belaPlatform
default_img: "/images/sept2016.jpg"

# Profile settings
name: 
profile_img: 
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
